# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('short_n', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_n', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'areas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Measurments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('p1', models.FloatField()),
                ('p2', models.SmallIntegerField()),
                ('p3', models.SmallIntegerField()),
                ('p4', models.FloatField()),
                ('checked', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'measurments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station', models.SmallIntegerField()),
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('point_x', models.FloatField()),
                ('point_y', models.FloatField()),
                ('point_z', models.FloatField()),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_lab.Areas')),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='measurments',
            name='base_station',
            field=models.ForeignKey(db_column='base_station', on_delete=django.db.models.deletion.CASCADE, to='db_lab.Stations'),
        ),
        migrations.AlterUniqueTogether(
            name='stations',
            unique_together=set([('station', 'area')]),
        ),
        migrations.AlterUniqueTogether(
            name='measurments',
            unique_together=set([('date', 'time', 'base_station')]),
        ),
    ]
