# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurments',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
