# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0004_areas_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='test',
        ),
    ]
