# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0005_remove_areas_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station_role',
            old_name='type',
            new_name='station_type',
        ),
        migrations.AlterField(
            model_name='stations',
            name='role',
            field=models.ForeignKey(blank=True, db_column='station_role', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_lab.station_role'),
        ),
    ]
