# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0006_auto_20171024_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='role',
        ),
        migrations.AddField(
            model_name='measurments',
            name='p7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurments',
            name='p1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='measurments',
            name='p2',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='measurments',
            name='p3',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='measurments',
            name='p4',
            field=models.FloatField(blank=True),
        ),
        migrations.DeleteModel(
            name='Station_role',
        ),
    ]
