# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0007_auto_20171024_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_type', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('p7_value', models.FloatField(blank=True, null=True, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stations',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_lab.StationRole'),
        ),
    ]
