# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0008_auto_20171025_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='role',
        ),
        migrations.DeleteModel(
            name='StationRole',
        ),
    ]
