# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0009_auto_20171025_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_type', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('p7_value', models.FloatField(blank=True, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'station_role',
            },
        ),
    ]
