# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0010_stationrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_lab.StationRole'),
        ),
    ]
