# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0011_stations_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurments',
            name='p7',
        ),
    ]
