# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_lab', '0012_remove_measurments_p7'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurments',
            name='p7',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
